# Generated by Django 4.0.4 on 2022-04-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choise_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Question_text',
            new_name='question_text',
        ),
    ]
